<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NullabilityInfoContextSupport>true</NullabilityInfoContextSupport>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>

    <!-- Force inclusion of Blazor framework files -->
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MyPo.Shared\MyPo.Shared.csproj" />
    <ProjectReference Include="..\MyPo.Blazor.App\MyPo.Blazor.App.csproj" />
    <ProjectReference Include="..\..\MyPo.Libs\MyPo.Libs.csproj" />
    <ProjectReference Include="..\MyPo.Blazor.Portfolio.App\MyPo.Blazor.Portfolio.App.csproj" />
  </ItemGroup>

</Project>
