<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyPo.Shared\MyPo.Shared.csproj" />
    <ProjectReference Include="..\MyPo.Shared.EF\MyPo.Shared.EF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Finance.NET" Version="1.1.13" />
  </ItemGroup>

</Project>
