<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Force inclusion of Blazor framework files -->
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyPo.Blazor.App\MyPo.Blazor.App.csproj" />
    <ProjectReference Include="..\..\MyPo.Portfolio.Shared\MyPo.Portfolio.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.45.0" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.10" />
  </ItemGroup>

</Project>
