<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyPo.Blazor.App\MyPo.Blazor.App.csproj" />
    <ProjectReference Include="..\..\MyPo.Portfolio.Shared\MyPo.Portfolio.Shared.csproj" />
  </ItemGroup>

</Project>
