using System.Text.Json.Serialization;
using MyPo.Shared.Models;

namespace MyPo.Portfolio.Shared.Models;

public enum ReportType
{
    // UNKNOWN,
    WEEKLY,
    MONTHLY,
    QUARTERLY,
    YEARLY
}

public sealed class ReportEntity : Entity<string>
{
    /// <summary>
    /// A marker txtype for position reports, which are generated by the system to represent the current position of a symbol in a portfolio.
    /// </summary>
    public static string TX_TYPE_POSITION = "POSITION";

    /// <summary>
    /// A marker item code for reports that represent the entire portfolio, rather than a specific symbol.
    /// </summary>
    public static string ITEM_CODE_ENTIRE_PORTFOLIO = "*";

    /// <inheritdoc />
    public override string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// Report type: WEEKLY, MONTHLY, QUARTERLY, YEARLY
    /// </summary>
    public ReportType Type { get; set; } = default!;

    /// <summary>
    /// YYYY-MM-DD, mark the start date of the report period
    /// </summary>
    public string PeriodStart { get; set; } = default!;

    /// <summary>
    /// Period label: FY2024-25-W01 for weekly, 2024-01 for monthly, FY2024-25-Q1 for quarterly, FY2024-25 for yearly
    /// </summary>
    public string PeriodLabel { get; set; } = default!;

    public string PortfolioId { get; set; } = default!;

    /// <summary>
    /// Item code in the format EXCHANGE:SYMBOL, e.g. NASDAQ:AAPL
    /// </summary>
    public string ItemCode { get; set; } = default!;

    /// <summary>
    /// Transaction type: BUY, SELL, DIVIDEND, etc.
    /// </summary>
    public string TxType { get; set; } = default!;

    /// <summary>
    /// Additional report data (quantity, cost, open/close value, ...). Stored as a JSON document so new
    /// fields can be added without changing the database schema.
    /// </summary>
    public ReportEntityMetadata? Metadata { get; set; }

    public bool IsFinal { get; set; } = false;
}

/// <summary>
/// Metadata for a <see cref="ReportEntity"/>, persisted as a JSON document. Holding the report's numeric
/// figures here (instead of as dedicated columns) lets new fields be introduced without schema changes.
/// </summary>
public sealed class ReportEntityMetadata
{
    [JsonPropertyName("quantity"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? Quantity { get; set; }

    [JsonPropertyName("accumulated_quantity"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? AccumulatedQuantity { get; set; }

    // [JsonPropertyName("cost"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    // public decimal? Cost { get; set; }
    [JsonIgnore]
    public decimal Cost => (Buys ?? 0m) - (Sells ?? 0m);

    // [JsonPropertyName("accumulated_cost"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    // public decimal? AccumulatedCost { get; set; }
    [JsonIgnore]
    public decimal AccumulatedCost => (AccumulatedBuys ?? 0m) - (AccumulatedSells ?? 0m);

    [JsonPropertyName("buys"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? Buys { get; set; }

    [JsonPropertyName("accumulated_buys"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? AccumulatedBuys { get; set; }

    [JsonPropertyName("sells"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? Sells { get; set; }

    [JsonPropertyName("accumulated_sells"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? AccumulatedSells { get; set; }

    [JsonPropertyName("open_value"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? OpenValue { get; set; }

    [JsonPropertyName("close_value"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? CloseValue { get; set; }

    [JsonPropertyName("tax"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? Tax { get; set; }

    [JsonPropertyName("accumulated_tax"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? AccumulatedTax { get; set; }

    [JsonPropertyName("fees"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? Fees { get; set; }

    [JsonPropertyName("accumulated_fees"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? AccumulatedFees { get; set; }

    [JsonPropertyName("interest"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? Interest { get; set; }

    [JsonPropertyName("accumulated_interest"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? AccumulatedInterest { get; set; }

    [JsonPropertyName("cashin"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? Cashin { get; set; }

    [JsonPropertyName("accumulated_cashin"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? AccumulatedCashin { get; set; }

    [JsonPropertyName("cashout"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? Cashout { get; set; }

    [JsonPropertyName("accumulated_cashout"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? AccumulatedCashout { get; set; }

    [JsonPropertyName("dividends"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? Dividends { get; set; }

    [JsonPropertyName("accumulated_dividends"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? AccumulatedDividends { get; set; }

    [JsonPropertyName("distributions"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? Distributions { get; set; }

    [JsonPropertyName("accumulated_distributions"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? AccumulatedDistributions { get; set; }

    /// <summary>Period net cash flow (derived, not persisted).</summary>
    [JsonIgnore]
    public decimal Cash =>
        (Cashin ?? 0m) - (Cashout ?? 0m)
        - (Cost/* ?? 0m*/)                                   // Cost = buys - sells
        + (Dividends ?? 0m) + (Distributions ?? 0m) + (Interest ?? 0m)
        - (Tax ?? 0m) - (Fees ?? 0m);

    /// <summary>Running cash balance through this period (derived, not persisted).</summary>
    [JsonIgnore]
    public decimal AccumulatedCash =>
        (AccumulatedCashin ?? 0m) - (AccumulatedCashout ?? 0m)
        - (AccumulatedCost/* ?? 0m*/)
        + (AccumulatedDividends ?? 0m) + (AccumulatedDistributions ?? 0m) + (AccumulatedInterest ?? 0m)
        - (AccumulatedTax ?? 0m) - (AccumulatedFees ?? 0m);
}

public sealed class ReportPeriod
{
    /// <summary>
    /// Report type: WEEKLY, MONTHLY, QUARTERLY, YEARLY
    /// </summary>
    [JsonPropertyName("type")]
    public ReportType Type { get; set; } = default!;

    /// <summary>
    /// Report period start date, formatted as yyyy-MM-dd.
    /// </summary>
    [JsonPropertyName("start")]
    public string Start { get; set; } = default!;

    [JsonPropertyName("label")]
    public string Label { get; set; } = default!;
}
