<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- TODO: temporarily suspend error on duplicate publish output files; will be removed once the issue is resolved -->
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>

    <UserSecretsId>fa9f8b33-d379-4187-8cbb-604ddcb434e6</UserSecretsId>

     <!-- Force inclusion of Blazor framework files -->
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.25" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MyPo.Api\MyPo.Api.csproj" />
    <ProjectReference Include="..\MyPo.Blazor.Client\MyPo.Blazor.Client.csproj" />
    <ProjectReference Include="..\MyPo.Blazor.App\MyPo.Blazor.App.csproj" />
    <ProjectReference Include="..\..\MyPo.Libs\MyPo.Libs.csproj" />
    <ProjectReference Include="..\..\MyPo.Portfolio.Api\MyPo.Portfolio.Api.csproj" />
    <ProjectReference Include="..\MyPo.Blazor.Portfolio.App\MyPo.Blazor.Portfolio.App.csproj" />
  </ItemGroup>

  <!-- Prevents duplicated files from other projects from being copied to the output directory -->
  <!-- <ItemGroup>
    <Content Include="..\..\MyPo.Api\appsettings.json">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Remove="..\..\MyPo.Api\appsettings.json;..\..\MyPo.Api\appsettings.Development.json" />
    <None Remove="..\..\MyPo.Api\appsettings.json;..\..\MyPo.Api\appsettings.Development.json" />
    <Compile Remove="..\..\MyPo.Api\appsettings.json;..\..\MyPo.Api\appsettings.Development.json" />
    <EmbeddedResource Remove="..\..\MyPo.Api\appsettings.json;..\..\MyPo.Api\appsettings.Development.json" />
  </ItemGroup> -->

  <!-- Prevent other development setting files from being copied to the output directory -->
  <!-- <ItemGroup>
    <Content Update="..\MyPo.Blazor.Client\wwwroot\appsettings.Development.json;appsettings.Development.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup> -->
</Project>
